language: cpp

cache: ccache

branches:
  only:
    - master

compiler:
  - gcc

env:
  matrix:
    - COMPILER=g++-8.1 CCOMPILER=gcc-8.1 PUSH_COVERAGE=ON
    - COMPILER=g++-8.2 CCOMPILER=gcc-8.2
    - COMPILER=clang++-5.0 CCOMPILER=clang-5.0

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
      - llvm-toolchain-precise
      - llvm-toolchain-precise-5.0
    packages:
      - g++-8.1
      - g++-8.2
      - clang-5.0
      - libboost1.65-all-dev
      - python-pip

install:
  - if [ "$PUSH_COVERAGE" == "ON" ]; then pip install --user cpp-coveralls; fi

before_script:
  - export CXX=$COMPILER CC=$CCOMPILER
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..

script: make -j4 && ctest -V -j4
after_success:
  - cd ..
  - if [ "$PUSH_COVERAGE" == "ON" ]; then coveralls --gcov gcov-8.1 -i include --gcov-options '\-lp'; fi
